// src/mockData.js
export const mockHealthRecords = [
  { id: 1, 
    type: "Cá Thể", 
    name: "Panthera leo", 
    ageOrCount: "5 tuổi", 
    health: "Khỏe mạnh", 
    height: "60 cm", 
    weight: "125 kg", 
    sex: "Đực",
    creatorName: "Nguyễn Văn A", 
    creatorID: "012345678904", 
    vaccinationID: "101", 
    vaccinationDate: "2024-01-10", 
    vaccinationMethod: "Tiêm Bắp", 
    vaccineType: "Vaccine A", 
    vaccineDose: "10 ml", 
    vaccinationReaction: "Không phản ứng", 
    treatmentID: "201", 
    symptom: "Sốt", 
    diagnosis: "Cảm Lạnh", 
    treatmentResult: "Khỏi", 
    medicineType: "Paracetamol", 
    notes: "Uống đủ liều",
  },
  { id: 2, 
    type: "Nhóm", 
    name: "Equus ferus caballus", 
    ageOrCount: "20 con", 
    health: "Khỏe mạnh", 
    height: "125 cm", 
    weight: "125 kg", 
    sex: "Cái",
    creatorName: "Nguyễn Văn B", 
    creatorID: "012345678905", 
    vaccinationID: "102", 
    vaccinationDate: "2023-12-05", 
    vaccinationMethod: "Tiêm Bắp", 
    vaccineType: "Vaccine B", 
    vaccineDose: "15 ml", 
    vaccinationReaction: "Phản ứng nhẹ", 
    treatmentID: "202", 
    symptom: "Ho", 
    diagnosis: "Viêm Phế Quản", 
    treatmentResult: "Khỏi", 
    medicineType: "Ambroxol", 
    notes: "Dùng theo chỉ dẫn bác sĩ",
  },
  { id: 3, 
    type: "Cá Thể", 
    name: "Panthera tigris", 
    ageOrCount: "7 tuổi", 
    health: "Bình thường", 
    height: "110 cm", 
    weight: "115 kg", 
    sex: "Cái",
    creatorName: "Nguyễn Văn C", 
    creatorID: "012345678906", 
    vaccinationID: "103", 
    vaccinationDate: "2022-11-15", 
    vaccinationMethod: "Tiêm Dưới Da", 
    vaccineType: "Vaccine C", 
    vaccineDose: "20 ml", 
    vaccinationReaction: "Không phản ứng", 
    treatmentID: "203", symptom: "Sổ mũi", 
    diagnosis: "Cảm Cúm", 
    treatmentResult: "Khỏi", 
    medicineType: "Oseltamivir", 
    notes: "Uống sau ăn",
  },
  { id: 4, 
    type: "Cá Thể", 
    name: "Panthera pardus", 
    ageOrCount: "4 tuổi", 
    health: "Tốt", 
    height: "95 cm", 
    weight: "90 kg", 
    sex: "Đực",
    creatorName: "Nguyễn Văn D", 
    creatorID: "012345678907", 
    vaccinationID: "104", 
    vaccinationDate: "2023-08-20", 
    vaccinationMethod: "Tiêm Bắp", 
    vaccineType: "Vaccine D", 
    vaccineDose: "12 ml", 
    vaccinationReaction: "Không phản ứng", 
    treatmentID: "204", 
    symptom: "Đau Bụng", 
    diagnosis: "Rối Loạn Tiêu Hóa", 
    treatmentResult: "Khỏi", 
    medicineType: "Metronidazole", 
    notes: "Uống với thức ăn",
  },
  { id: 5, 
    type: "Nhóm", 
    name: "Giraffa camelopardalis", 
    ageOrCount: "10 con", 
    health: "Khỏe mạnh", 
    height: "550 cm", 
    weight: "1200 kg", 
    sex: "Đực",
    creatorName: "Nguyễn Văn E", 
    creatorID: "012345678908", 
    vaccinationID: "105", 
    vaccinationDate: "2024-02-25", 
    vaccinationMethod: "Tiêm Bắp", 
    vaccineType: "Vaccine E", 
    vaccineDose: "25 ml", 
    vaccinationReaction: "Phản ứng nhẹ", 
    treatmentID: "205", 
    symptom: "Đau chân", 
    diagnosis: "Chấn Thương Nhẹ", 
    treatmentResult: "Khỏi", 
    medicineType: "Ibuprofen", 
    notes: "Nghỉ ngơi và theo dõi",
  }
];
  